### ISSUE TITLE
UI feedback: dots in schedule view can be somewhat confusing

### ISSUE THREAD

**Issue by keunes** [pretalx/schedule#8]
As this holds something between a (UX) 'bug' and a feature request, I'm posting it here.

Via [JoinUp](https://joinup.ec.europa.eu/collection/open-source-observatory-osor/event/online-event-matomo-camp) I just came across MatomoCamp's pretalx instance: https://schedule.matomocamp.org/matomocamp-2021/schedule/

As the issue title says: the dots in the schedule view can be somewhat confusing. My colleague pointed this out when viewing the schedule:
> the dots there makes me think that there is a visualisation issue

I suppose the dots are displayed to indicate when the schedule/timeline is 'collapsed' because there are no sessions. However, they are also displayed when there's just an empty calendar slot, while the calendar is actually not collapsed:
![image](https://user-images.githubusercontent.com/11229646/137096526-d4a455c3-5e11-4285-a69e-eaf294688a3d.png)

In that situation the dots are more confusing then helping. I would expect that **if the view is not collapsed the dots are not displayed**.

And related feedback: The collapsed rows feel somewhat unbalanced, because a time is displayed at the top and nothing is displayed at the bottom. Instead, I would expect a **collapsed section to not display anything apart from the dots**. This creates a calmer view and also helps

<details>
<summary>I'm wondering also whether it would be helpful to NOT collapse the calendar if there's just two (2) empty rows</summary>
(Slices, in this case, of 30 minutes - I don't know if that varies per event/situation). So only collapse if there are 3 or more empty rows. It visualises the time one has available (e.g. to go for lunch elsewhere), without having to carefully look at the numbers (hours) displayed to indicate the times. And with two rows not much vertical space is taken.

**Comment by rixx** [comment]
Not displaying the dots for 30 minute slices is definitely a good idea, I'm currently implementing this. I'm also considering if it wouldn't be better to do the same for 60 minute slices, since those don't feel really collapsed …

As for the second part: skipping the collapse on two consecutive empty slices would have to be limited to the middle of the day (we don't want useless empty lines beginning and trailing). We would have to try it out – currently, I'm not convinced this would look well, but we'd probably need to try out some scenarios to make sure of that.
